{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "00b39b40",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting rasterio\n",
      "  Using cached rasterio-1.2.6.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.2.5.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.2.4.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.2.3.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.2.2.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.2.1.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-dfsdwunc\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/d6/61/f083df6539a3ad5ddb480dd5551d55039b9f59948c68415a9737ea62081a/rasterio-1.2.6.tar.gz#sha256=24975b97fe2fc3fd282d59640baab19de431448e1b23be6b85b68fecc1362f88 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-dfsdwunc\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-tdd6qucd\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/5c/a3/2f30c89323826cba9344b55d3355df16695dff14aa312dbddb8050bb571f/rasterio-1.2.5.tar.gz#sha256=dbf85c2c3dbdc5000cb0afc24bd7625ff696bd8698661fed23d115164333d80f (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-tdd6qucd\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-gw86wx29\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "  Using cached rasterio-1.2.0.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.8.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.7.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.6.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.5.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.4.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.3.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.2.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.1.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.1.0.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.0.28.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.0.27.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.0.26.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.0.25.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  Using cached rasterio-1.0.24.tar.gz (1.9 MB)\n",
      "  Using cached rasterio-1.0.23.tar.gz (1.9 MB)\n",
      "  Using cached rasterio-1.0.22.tar.gz (1.9 MB)\n",
      "  Using cached rasterio-1.0.21.tar.gz (1.9 MB)\n",
      "  Using cached rasterio-1.0.20.tar.gz (1.9 MB)\n",
      "  Using cached rasterio-1.0.18.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.17.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.16.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.15.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.14.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.13.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.12.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.11.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.10.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.9.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.8.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.7.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.6.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.5.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.4.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.3.post1.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.3.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.2.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.1.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-1.0.0.tar.gz (1.8 MB)\n",
      "  Using cached rasterio-0.36.0.tar.gz (1.2 MB)\n",
      "Requirement already satisfied: affine in c:\\users\\desmond\\anaconda3\\lib\\site-packages (from rasterio) (2.3.0)\n",
      "Requirement already satisfied: cligj in c:\\users\\desmond\\anaconda3\\lib\\site-packages (from rasterio) (0.7.2)\n",
      "Requirement already satisfied: numpy in c:\\users\\desmond\\anaconda3\\lib\\site-packages (from rasterio) (1.20.1)\n",
      "Requirement already satisfied: snuggs in c:\\users\\desmond\\anaconda3\\lib\\site-packages (from rasterio) (1.4.7)\n",
      "Requirement already satisfied: click-plugins in c:\\users\\desmond\\anaconda3\\lib\\site-packages (from rasterio) (1.1.1)\n",
      "Requirement already satisfied: click>=4.0 in c:\\users\\desmond\\anaconda3\\lib\\site-packages (from click-plugins->rasterio) (7.1.2)\n",
      "Requirement already satisfied: pyparsing>=2.1.6 in c:\\users\\desmond\\anaconda3\\lib\\site-packages (from snuggs->rasterio) (2.4.7)\n",
      "Building wheels for collected packages: rasterio\n",
      "  Building wheel for rasterio (setup.py): started\n",
      "  Building wheel for rasterio (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for rasterio\n",
      "Failed to build rasterio\n",
      "Installing collected packages: rasterio"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/64/22/a8a0d384147fcbb2ecdea0a05d7d178e8692c62659fe733bd4b3966e6e95/rasterio-1.2.4.tar.gz#sha256=31248c5ddc8f138f73b166dd93384aa72d11abd0dc27dca90a190276c7976aa3 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-gw86wx29\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-pvwi49rm\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "    Running setup.py install for rasterio: started\n",
      "    Running setup.py install for rasterio: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/97/85/3591f1b04fc9e9038aff7d6c5ddc816e8a7c0c8362f69b70ed6455ebcebd/rasterio-1.2.3.tar.gz#sha256=d8c345e01052b70ac3bbbe100c83def813c0ab19f7412c2c98e553d03720c1c5 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-pvwi49rm\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-m2zqh5r9\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/b3/e9/f7092cd8ac97f1b2a6f15bfc084b496d40653dd188dd0945cfe1bbd67abe/rasterio-1.2.2.tar.gz#sha256=8187d01f30d4e01e93f0a434df6a4cc63dd026a18b5287c242b066cb56223424 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-m2zqh5r9\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython==0.29.21 oldest-supported-numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-kxfmc50a\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/cf/15/79f2ed3d25b02ace4c3a07168ef4a3ff34afc86537d118fd25230df6830f/rasterio-1.2.1.tar.gz#sha256=81d4181514c67dc660d7b8cf943ad55c4fb3e0a17ac893d92628ac928cfab3d8 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-kxfmc50a\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-lge3b9lu\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/b9/bc/3bcf9fb9139112e389a4c8b914c45dac01981db211d18dae7af5a081c781/rasterio-1.2.0.tar.gz#sha256=d1c70ae16f4048dce8292a607f016833c024c941b3eca51cd773fc494172c6eb (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-lge3b9lu\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-bekoegu1\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/73/2d/3e1bc56d75bf7c4cd5df51536992b3420197f2aa5ddd4d93e12100715dff/rasterio-1.1.8.tar.gz#sha256=f7cac7e2ecf65b4b1eb78c994c63bd429b67dc679b0bc0ecfe487d3d5bf88fd5 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-bekoegu1\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-2t000dev\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/50/bf/35e564093d84509406c3d96e147132067ddbc591966b9b52c3aa0331f1b8/rasterio-1.1.7.tar.gz#sha256=8418c024f9bf7350d03855039d2700064532bae33a3c6ee885c8b6c8fc13415a (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-2t000dev\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-gldv6xxp\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/c0/e0/a055775339c04db97a92254b08d70a796ff0cc8b4c9a23f92daa1dc96612/rasterio-1.1.6.tar.gz#sha256=c098881dfe301c5e3aa43a3171985fb365d64dc4d1c0a1d8288c7870fb240efe (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-gldv6xxp\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-rq0la6hy\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/86/43/aae52a19a69ee30d28d0374c5f22d473ba3ba98ace4a5a5330a26590df95/rasterio-1.1.5.tar.gz#sha256=ebe75c71f9257c780615caaec8ef81fa4602702cf9290a65c213e1639284acc9 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-rq0la6hy\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-jjo9z_0p\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/3a/61/c91a2faa4e7bd1b3ec915d8cb9fb6cf16fe5b85e967c0336c9f0ec837ca0/rasterio-1.1.4.tar.gz#sha256=5d7393f3a690a91813022452022df1d5a3a2c732019f24f2bd0b051fd47a03c1 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-jjo9z_0p\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-ig7d6oi5\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/d2/8a/8a7c67e75092cea6de3347db5e9e65011def24da8e632a0dd74253733d5a/rasterio-1.1.3.tar.gz#sha256=fe2eac942ae4f8a97246c8cd3977723997817b53a9058cf1959551026c6177e7 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-ig7d6oi5\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-z7hkx2f0\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/06/f1/dd83f3ad863a98ac543e19abd485bce1ba7e545c79a64cc186668fa49aa9/rasterio-1.1.2.tar.gz#sha256=f6df894e37eefb408e4562ab9c14efcf027b0f5f279be5ff8b2105d03f2d3c37 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-z7hkx2f0\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-vkstu2wr\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/9b/f1/c178b41a94ab6bfb4d64a224092d7549a5b8618ce21ae644e203f56a0efa/rasterio-1.1.1.tar.gz#sha256=7571ff5b96aeb9b1ac83d56534895c0e3d5e8678568375cf83c87111e2856fcb (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-vkstu2wr\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-4s6hbdtx\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/1a/6d/ee8b15e0d45dd7e9e7f2559e37f91915a19155cf8403948ff2082903ee30/rasterio-1.1.0.tar.gz#sha256=77aa68860da9d9382cee0294b78809b04ad4f884ea95d1dec084f2f9bab105e8 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-4s6hbdtx\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-l73qkm4z\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/f7/03/1dcc14b0c77ec4c4ca4bd917527bc41fdbba49f56015d535f3d781c826aa/rasterio-1.0.28.tar.gz#sha256=9def7698e7076c8f148e8bfa0b2a3334308b2f5311abe9e40269e0bf9dfc645d (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-l73qkm4z\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-bhvfq1b0\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ac/d9/c369236ff112376a298bbd615471b6786e8974656c66e9db679f432f8932/rasterio-1.0.27.tar.gz#sha256=403d2c80cddd6395f3fe5474f43333415dc0dcf430d861de82234988d20d6147 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-bhvfq1b0\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-btknp9qa\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/30/7c/c66b72339b17dfb58f2260473b575ed875216c4de8f579883ef3690b8759/rasterio-1.0.26.tar.gz#sha256=9d5246631b2295b9fb417f220d009a1954aeb5895c9e27bab71fc143f4ba5633 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-btknp9qa\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-h7nl7__y\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_internal\\index\\collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\requests\\certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip\\_vendor\\certifi\\core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\importlib\\resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/0c/62/91d23e91e7c2b6db1ba208c1e1ced59554a0e651087bf0a854d915f08d10/rasterio-1.0.25.tar.gz#sha256=f821efe923098bd9b1792553a9f5282f6aefdb8fa638e7d966dbcdc50b6b0333 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' 'C:\\Users\\DESMOND\\anaconda3\\lib\\site-packages\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-build-env-h7nl7__y\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_cc51565475874b9cac72c0534b5a1cd7\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_cc51565475874b9cac72c0534b5a1cd7\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-6_hhe8e6'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_cc51565475874b9cac72c0534b5a1cd7\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/57/84/be5689470a73f5f8988cf44b81cb3493ebb8abbbebb69768c8fc86fccdd5/rasterio-1.0.24.tar.gz#sha256=4839479621045211f66868ec49625979693450bc2e476f23e7e8ac4804eaf452 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5536ec6847604478a20355a2a98805be\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5536ec6847604478a20355a2a98805be\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-icu7qv8y'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_5536ec6847604478a20355a2a98805be\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/46/ee/f9b4bfb55b6cf1b5562e0b16bc75ab2ca3810587753e4c9944279d75540c/rasterio-1.0.23.tar.gz#sha256=45e1a4b3c5c58a0b9f1a6bfd0aa08bdc15da57fa690a1f6f26d1a6a3d3cc7aa5 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_1d5dcff1438d4e278e89646d7bb78dc5\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_1d5dcff1438d4e278e89646d7bb78dc5\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-s4exge2p'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_1d5dcff1438d4e278e89646d7bb78dc5\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ce/90/8af39cdfed9a40bd59801f101f74eab5f1562d3557806ddfa2ed86d4be0b/rasterio-1.0.22.tar.gz#sha256=31c68b1ed8684ccc4855daeb9fe6c42bf5d54bbade8f2ab225370b7169422d7d (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_cccf7e6d59f04b718af575cd110fc4ef\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_cccf7e6d59f04b718af575cd110fc4ef\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-c3r126vf'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_cccf7e6d59f04b718af575cd110fc4ef\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/b4/0f/c5a412208f217bba892e5482c1129df29bdfe474a069aba36407ee68c518/rasterio-1.0.21.tar.gz#sha256=5dbe570d381e6bec0da703a92ebf543ca01d9b34ac6ad5f3791fdf0a7aab27a3 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_f5a9dca2c77b4d3381170e4ee8fb25c8\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_f5a9dca2c77b4d3381170e4ee8fb25c8\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-hd2jvnt5'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_f5a9dca2c77b4d3381170e4ee8fb25c8\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/75/88/1abc8a5128a66790d7e99ec3a6139d41ffd8f4fb0471218cfa3ce4e5ce4b/rasterio-1.0.20.tar.gz#sha256=820799cfd650d1518b52da9058a89a8d5452743d7593f3a57eab267b6a63b341 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5c339b52a18c4a76a9258389d8f05887\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5c339b52a18c4a76a9258389d8f05887\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-dx4yhc1v'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_5c339b52a18c4a76a9258389d8f05887\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/4e/79/b3e2d1783cde76d31eb87fa859eadf6855743d18c52942fbaa5f638e98a9/rasterio-1.0.18.tar.gz#sha256=02eabc24a2e1e323ebda385c608183a66ab56e46ff2077ac2aecd0f6ac3c3ea5 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5f04465386ca40eabdaca408d9d070cb\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5f04465386ca40eabdaca408d9d070cb\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-oakhn4b3'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_5f04465386ca40eabdaca408d9d070cb\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/23/40/6bf2f3e50e5e89a6c2efad33e3409a0133129aa8bba66a4540dc0912f807/rasterio-1.0.17.tar.gz#sha256=0f346fdfb65ef166e640f19a25fdceb834c49091e4141b5e613a8b90d3a8ad80 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_c3053e24e0c7415dbe3a329e7885dd11\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_c3053e24e0c7415dbe3a329e7885dd11\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-ntyb6v2h'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_c3053e24e0c7415dbe3a329e7885dd11\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ee/81/29b30295af0cd7fddb3a0c4b2fc6c57ac0571e1d33c88c340e8cd53da25b/rasterio-1.0.16.tar.gz#sha256=8010425eb7804cfa3785ae2f59ddcd9f8de51d03516719d084e84e80c89ee955 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_90d41f6f84fb4633adaa14a7408021e5\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_90d41f6f84fb4633adaa14a7408021e5\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-f9rakvmr'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_90d41f6f84fb4633adaa14a7408021e5\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/f3/7a/c9ea37324b40e04875aa776350bd3671add21fa64eceef0e552bd9697c20/rasterio-1.0.15.tar.gz#sha256=d35a9849d4947f7dc75f25024cad034f3cd7275d72a7d37a7c3376e01371a3ce (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5f84b765958442a2b466db8bdda61c6c\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5f84b765958442a2b466db8bdda61c6c\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-oxqstqtf'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_5f84b765958442a2b466db8bdda61c6c\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/14/f9/f6cdd44ddb8d390ebab7d0b2f9e4180a9cd605d28d093b0307c7ec312baa/rasterio-1.0.14.tar.gz#sha256=c63cfd18d1b26322371dc193bfff93dbb035a3f89b65d9675b424fd7dd57b881 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_abddb056bb2049ec8fd36ef0d5457cad\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_abddb056bb2049ec8fd36ef0d5457cad\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-lu309y_j'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_abddb056bb2049ec8fd36ef0d5457cad\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/d1/da/5ccbaed45770f37520f8ae97c5e16f507b92a3951a3c40eea46fbfae731a/rasterio-1.0.13.tar.gz#sha256=812c54ba444a9a7967bfd73256a058d6dd8cdfa810145fe44320eb5b5dfc9c48 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_45606612659f406ea12acba6b55ca716\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_45606612659f406ea12acba6b55ca716\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-73ing1wn'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_45606612659f406ea12acba6b55ca716\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/9d/06/5f65bc41b119e7e68ff3a1dae8e285a9be37d9360550e275bde537a55399/rasterio-1.0.12.tar.gz#sha256=b01976bbadb8382573577b67b75b653cee1fec634f23a321e52dccaed53757e6 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_76ef97d681174c3a85a9213e39d2a38e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_76ef97d681174c3a85a9213e39d2a38e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-7kvkdxik'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_76ef97d681174c3a85a9213e39d2a38e\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/32/2f/75727c18e8de01aa67871f607af8aa8a9bfc57f6ca6a758c96ec774bcb72/rasterio-1.0.11.tar.gz#sha256=7064460314ea289f753bb6e48684a8537f3f6aa421ae9a785dc55d9926c6c9da (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_aa4ac0e9109b4aff901910f00cfc1610\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_aa4ac0e9109b4aff901910f00cfc1610\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-cr5uujsh'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_aa4ac0e9109b4aff901910f00cfc1610\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/86/0a/a4ef029e5d2b3fc3a0c9c8846e44ee35797d814ff4ab3cd0ac76fc002584/rasterio-1.0.10.tar.gz#sha256=26933c002ad5084b3b394136dec94d36f586b29564d9ee21817b7b5d073bc190 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_a3c7bff704164194baf7ade55c24fd3a\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_a3c7bff704164194baf7ade55c24fd3a\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-_bg5vjd_'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_a3c7bff704164194baf7ade55c24fd3a\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/e9/1e/e42550364e3472f10503586d2f76d740640c0b2d983b66280ec011ece03d/rasterio-1.0.9.tar.gz#sha256=8f6905bb1f0b5674f7eb289761d57fb24bd9471a994e0cc235963389eaa2cf9f (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_c43f39e6a0254f3e98de176c447bea4d\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_c43f39e6a0254f3e98de176c447bea4d\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-i_hl8mqx'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_c43f39e6a0254f3e98de176c447bea4d\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/1a/d5/6cad936ff9beb89e79b1dae946f3097c70f7ab71cda5a9e356aec2e9ce9b/rasterio-1.0.8.tar.gz#sha256=fd0c821f0dbf0cbba88cb394ee9f2bfa60677730381e356caaec1672c50e8dc0 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5fc6229c345b4f6292db06d8cabd6374\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5fc6229c345b4f6292db06d8cabd6374\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-9beul2ev'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_5fc6229c345b4f6292db06d8cabd6374\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ce/e3/86ef71d178887f2e365763607f974d5a70be9fbd422e4378bd8c16b8c306/rasterio-1.0.7.tar.gz#sha256=707ddebceb76a9bf0b7ac81b937370fd5eb0943342955941e636ca294cd1a60a (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_289f9bf9147c46828d4e986c344f2be4\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_289f9bf9147c46828d4e986c344f2be4\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-p3ysb87g'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_289f9bf9147c46828d4e986c344f2be4\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/fd/2d/e24fc955d9b8dbf152cc1f019267688324409ec27d17014f1a7adfa195af/rasterio-1.0.6.tar.gz#sha256=b3c6a10f17cc8477b677f4e3743684f6591d67cb289c3f676f8850c9bf0de564 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_73598dcb67ba48618e1d6b2feae2668f\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_73598dcb67ba48618e1d6b2feae2668f\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-kzmpynnp'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_73598dcb67ba48618e1d6b2feae2668f\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/8f/06/78d85a7a1a44b5cee5aaae62692a7cec0a94af09e827db9f753b4ff990a3/rasterio-1.0.5.tar.gz#sha256=530bc3018ccb66e0dd4d408a9f39566c43bac9768b68cde31fa24333c3d56685 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_cd1a0f4eadce4fd482b4e80146c2e322\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_cd1a0f4eadce4fd482b4e80146c2e322\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-m_7j8cip'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_cd1a0f4eadce4fd482b4e80146c2e322\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/66/f3/0a4f444d239896b3f7d60b205ba05d02fec62bc7ea8598f630f1d5a45ca4/rasterio-1.0.4.tar.gz#sha256=ed018f8c64b06cca0e9a89967862f6898be2cf91038fcff7a7ae598b18f194a7 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_248eff8675f541a097d0f32398cf11d6\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_248eff8675f541a097d0f32398cf11d6\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-z6m2bnue'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_248eff8675f541a097d0f32398cf11d6\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/a6/70/9ccbc9aac78db96c7b9291515ec3676ff2da6a746a0bd826bc84b3115a7b/rasterio-1.0.3.post1.tar.gz#sha256=949cd9ce0143e3e71171e5833c98713cb2fbda1e64aaf27d9e795ac8225a6319 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5f878077ce2f4027b971726639b940fc\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_5f878077ce2f4027b971726639b940fc\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-zfk_73xq'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_5f878077ce2f4027b971726639b940fc\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/e1/b3/e34a28e3243454d179fd085ec9f933fb2b879023c488479875c39f01ad43/rasterio-1.0.3.tar.gz#sha256=8fb24254f5296ab9468f578dd4c07783fda151f86e3f917e8b97fb1e2c02721c (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_c3969fbdad654e4e871deeeb65314ce0\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_c3969fbdad654e4e871deeeb65314ce0\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-zco0z1lg'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_c3969fbdad654e4e871deeeb65314ce0\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/7f/43/fb81ba30ddd3ba7cc6d381f4af35504cfd7ad7f1d46041850d03fc626c6a/rasterio-1.0.2.tar.gz#sha256=335eced9009852ce13517a88d4e05427c3fbda5f865e902e678612e2ab63b590 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_4264adc2fdfc4f158425b3809ad3a20a\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_4264adc2fdfc4f158425b3809ad3a20a\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-7xw6sad7'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_4264adc2fdfc4f158425b3809ad3a20a\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ef/e2/eea3c9fd760b2fd3c68152e287e18698a11997ca265bbcbde999c13f1521/rasterio-1.0.1.tar.gz#sha256=b96be3e541f9f7b672eaa7b41bbe68216b5dea3dc7bcd96ef00db3c2a9553b15 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_7c68ee8e1eab43a4a1f4502485750336\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_7c68ee8e1eab43a4a1f4502485750336\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-pip-egg-info-l1rm80f8'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_7c68ee8e1eab43a4a1f4502485750336\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/33/22/ad2ea27c9829582ab5280f35cc61e424970ce0add34e258c9e171a62cb73/rasterio-1.0.0.tar.gz#sha256=6f2e90f2b740d727b36e39550e2a949d52551717812f9b4748f9bc351d666274 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_26c2aee0028e456ca37f4f550b7b9ae1\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_26c2aee0028e456ca37f4f550b7b9ae1\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-wheel-56mt51nf'\n",
      "       cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_26c2aee0028e456ca37f4f550b7b9ae1\\\n",
      "  Complete output (63 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build\\lib.win-amd64-3.8\n",
      "  creating build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\compat.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\coords.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\crs.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\dtypes.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\enums.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\env.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\errors.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\features.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\fill.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\plot.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\profiles.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\sample.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\tool.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\transform.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\vfs.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\warp.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\windows.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  creating build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\bounds.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\calc.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\clip.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\convert.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\edit_info.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\env.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\helpers.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\info.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\insp.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\main.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\options.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\overview.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\rasterize.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\sample.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\shapes.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\stack.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\transform.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\warp.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  creating build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "  copying .\\rasterio\\tools\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "  copying .\\rasterio\\tools\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "  copying .\\rasterio\\tools\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "  running egg_info\n",
      "  writing rasterio.egg-info\\PKG-INFO\n",
      "  writing dependency_links to rasterio.egg-info\\dependency_links.txt\n",
      "  writing entry points to rasterio.egg-info\\entry_points.txt\n",
      "  writing requirements to rasterio.egg-info\\requires.txt\n",
      "  writing top-level names to rasterio.egg-info\\top_level.txt\n",
      "  reading manifest file 'rasterio.egg-info\\SOURCES.txt'\n",
      "  writing manifest file 'rasterio.egg-info\\SOURCES.txt'\n",
      "  running build_ext\n",
      "  building 'rasterio._base' extension\n",
      "  error: Microsoft Visual C++ 14.0 or greater is required. Get it with \"Microsoft C++ Build Tools\": https://visualstudio.microsoft.com/visual-cpp-build-tools/\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for rasterio\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_26c2aee0028e456ca37f4f550b7b9ae1\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_26c2aee0028e456ca37f4f550b7b9ae1\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-record-9qtzmdfd\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\DESMOND\\anaconda3\\Include\\rasterio'\n",
      "         cwd: C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-install-5u1pvumd\\rasterio_26c2aee0028e456ca37f4f550b7b9ae1\\\n",
      "    Complete output (63 lines):\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    creating build\n",
      "    creating build\\lib.win-amd64-3.8\n",
      "    creating build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\compat.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\coords.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\crs.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\dtypes.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\enums.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\env.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\errors.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\features.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\fill.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\plot.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\profiles.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\sample.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\tool.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\transform.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\vfs.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\warp.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\windows.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    copying .\\rasterio\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "    creating build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\bounds.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\calc.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\clip.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\convert.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\edit_info.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\env.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\helpers.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\info.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\insp.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\main.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\options.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\overview.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\rasterize.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\sample.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\shapes.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\stack.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\transform.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\warp.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    copying .\\rasterio\\rio\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "    creating build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "    copying .\\rasterio\\tools\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "    copying .\\rasterio\\tools\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "    copying .\\rasterio\\tools\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "    running egg_info\n",
      "    writing rasterio.egg-info\\PKG-INFO\n",
      "    writing dependency_links to rasterio.egg-info\\dependency_links.txt\n",
      "    writing entry points to rasterio.egg-info\\entry_points.txt\n",
      "    writing requirements to rasterio.egg-info\\requires.txt\n",
      "    writing top-level names to rasterio.egg-info\\top_level.txt\n",
      "    reading manifest file 'rasterio.egg-info\\SOURCES.txt'\n",
      "    writing manifest file 'rasterio.egg-info\\SOURCES.txt'\n",
      "    running build_ext\n",
      "    building 'rasterio._base' extension\n",
      "    error: Microsoft Visual C++ 14.0 or greater is required. Get it with \"Microsoft C++ Build Tools\": https://visualstudio.microsoft.com/visual-cpp-build-tools/\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: 'C:\\Users\\DESMOND\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_26c2aee0028e456ca37f4f550b7b9ae1\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\DESMOND\\\\AppData\\\\Local\\\\Temp\\\\pip-install-5u1pvumd\\\\rasterio_26c2aee0028e456ca37f4f550b7b9ae1\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\DESMOND\\AppData\\Local\\Temp\\pip-record-9qtzmdfd\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\DESMOND\\anaconda3\\Include\\rasterio' Check the logs for full command output.\n"
     ]
    }
   ],
   "source": [
    "! pip install rasterio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "729e51d6",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'rasterio'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-1-49582eaf759a>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mpydal\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mmatplotlib\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpyplot\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mplt\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 5\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mrasterio\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      6\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mpandas\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'rasterio'"
     ]
    }
   ],
   "source": [
    "import laspy\n",
    "import geopandas as gpd\n",
    "import pydal\n",
    "import matplotlib.pyplot as plt\n",
    "import rasterio\n",
    "import pandas\n",
    "import numpy as np\n",
    "from shapely.geometry import box, Point, Polygon"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "30228d0b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "79ea72a1",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "module 'laspy' has no attribute 'read'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-4-82a7fa469dd9>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mlas\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlaspy\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'data/laz/temp.laz'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m: module 'laspy' has no attribute 'read'"
     ]
    }
   ],
   "source": [
    "\n",
    "las = laspy.read('data/laz/temp.laz')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2ee68403",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'np' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-5-f5088718bb60>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0melevetions\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0marray\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlas\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mz\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'np' is not defined"
     ]
    }
   ],
   "source": [
    "elevetions = np.array(las.z)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "53ceaba8",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'elevetions' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-6-50260c809f49>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0mdf\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mgpd\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mGeoDataFrame\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mcolumns\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"elevation\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"geometry\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[0mdf\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'elevation'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0melevetions\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      3\u001b[0m \u001b[0mdf\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'geometry'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mgeometry_points\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[0mdf\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mgdf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mset_geometry\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"geometry\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'elevetions' is not defined"
     ]
    }
   ],
   "source": [
    "df = gpd.GeoDataFrame(columns=[\"elevation\", \"geometry\"])\n",
    "df['elevation'] = elevetions\n",
    "df['geometry'] = geometry_points\n",
    "df = gdf.set_geometry(\"geometry\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7cdc85ac",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'Polygon' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-7-821a6ac1f422>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0mMINX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mMINY\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mMAXX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mMAXY\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;33m-\u001b[0m\u001b[1;36m93.756155\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m41.918015\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m-\u001b[0m\u001b[1;36m93.747334\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m41.921429\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[0mpolygon\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mPolygon\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mMINX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mMINY\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mMINX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mMAXY\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mMAXX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mMAXY\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mMAXX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mMINY\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mMINX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mMINY\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      3\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[0mgrid\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mgpd\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mGeoDataFrame\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mpolygon\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mcolumns\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"geometry\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[0mgrid\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mset_crs\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mepsg\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m4326\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0minplace\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'Polygon' is not defined"
     ]
    }
   ],
   "source": [
    "MINX, MINY, MAXX, MAXY = [-93.756155, 41.918015, -93.747334, 41.921429]\n",
    "polygon = Polygon(((MINX, MINY), (MINX, MAXY), (MAXX, MAXY), (MAXX, MINY), (MINX, MINY)))\n",
    "\n",
    "grid = gpd.GeoDataFrame([polygon], columns=[\"geometry\"])\n",
    "grid.set_crs(epsg=4326, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b0750d01",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'grid' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-8-0d076aa986ec>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mminx\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mminy\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmaxx\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmaxy\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mgrid\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'geometry'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbounds\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'grid' is not defined"
     ]
    }
   ],
   "source": [
    "minx, miny, maxx, maxy = grid['geometry'][0].bounds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "bbb4ea65",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'minx' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-9-4be0d220a424>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mminx\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'minx' is not defined"
     ]
    }
   ],
   "source": [
    "minx"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "695a45bb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import laspy\n",
    "import geopandas as gpd\n",
    "from shapely.geometry import box, Point, Polygon\n",
    "\n",
    "\n",
    "\n",
    "class ElevationExtractor:\n",
    "    \n",
    "    def __init__(self, file_path: str, crs_epgs = 26915 ) -> None:\n",
    "        \n",
    "        self.file_path = file_path\n",
    "        self.las = self.__point_data_file(self.file_path)\n",
    "        self.crs_epgs = crs_epgs\n",
    "\n",
    "    def __point_data_file(self, path: str) -> dict:\n",
    "        try:\n",
    "            las = laspy.read(path)\n",
    "            return las\n",
    "\n",
    "        except FileNotFoundError as e:\n",
    "            print(\"File not found\")  \n",
    "    \n",
    "    def get_elevetion(self):\n",
    "        \n",
    "        geometry_points = [Point(x, y) for x, y in zip(self.las.x, self.las.y)]\n",
    "        elevetions = np.array(self.las.z)\n",
    "        \n",
    "        df = gpd.GeoDataFrame(columns=[\"elevation\", \"geometry\"])\n",
    "        df['elevation'] = elevetions\n",
    "        df['geometry'] = geometry_points\n",
    "        df = df.set_geometry(\"geometry\")\n",
    "        df.set_crs(epsg=self.crs_epgs , inplace=True)\n",
    "        \n",
    "        return df\n",
    "    \n",
    "    def covert_crs(self, crs_epgs: int, df: gpd.GeoDataFrame) -> gpd.GeoDataFrame:\n",
    "        \n",
    "        df['geometry'] = df['geometry'].to_crs(crs_epgs)\n",
    "        return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "ae87b292",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "module 'laspy' has no attribute 'read'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-11-06ba820bbdf7>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mee\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mElevationExtractor\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'data/laz/temp.laz'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m<ipython-input-10-a5b44cb88774>\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, file_path, crs_epgs)\u001b[0m\n\u001b[0;32m     10\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     11\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfile_path\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfile_path\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 12\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mlas\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__point_data_file\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfile_path\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     13\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcrs_epgs\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcrs_epgs\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     14\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m<ipython-input-10-a5b44cb88774>\u001b[0m in \u001b[0;36m__point_data_file\u001b[1;34m(self, path)\u001b[0m\n\u001b[0;32m     15\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m__point_data_file\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpath\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mstr\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m->\u001b[0m \u001b[0mdict\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     16\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 17\u001b[1;33m             \u001b[0mlas\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlaspy\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpath\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     18\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0mlas\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     19\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAttributeError\u001b[0m: module 'laspy' has no attribute 'read'"
     ]
    }
   ],
   "source": [
    "ee = ElevationExtractor('data/laz/temp.laz')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "f7bea5da",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'ee' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-12-d4db8cab4867>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mres\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mee\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_elevetion\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'ee' is not defined"
     ]
    }
   ],
   "source": [
    "\n",
    "res = ee.get_elevetion()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "3f1db55b",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'polygon' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-13-8a467780c301>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpolygon\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'polygon' is not defined"
     ]
    }
   ],
   "source": [
    "str(polygon)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "43c0bf41",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'ee' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-14-a3894d00f071>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mres2\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mee\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcovert_crs\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m4326\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mres\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'ee' is not defined"
     ]
    }
   ],
   "source": [
    "res2 = ee.covert_crs(4326, res)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "49c71ab3",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'polygon' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-15-ed5a9d0b05de>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpolygon\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbounds\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'polygon' is not defined"
     ]
    }
   ],
   "source": [
    "\n",
    "str(polygon.bounds)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "0bcd6f07",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pdal'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-16-0caf75d6ce3b>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mgeopandas\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mgpd\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mpdal\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      4\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mjson\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mErrorMsgs\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'pdal'"
     ]
    }
   ],
   "source": [
    "import geopandas as gpd\n",
    "\n",
    "import pdal\n",
    "import json\n",
    "import ErrorMsgs\n",
    "\n",
    "from boundaries import Boundaries\n",
    "\n",
    "\n",
    "err_msgs = ErrorMsgs.getErrorObj()\n",
    "\n",
    "\n",
    "class Lidar_Data_Fetch2:\n",
    "\n",
    "    def __init__(self, public_data_url, fetch_json_path=\"./fetch.json\") -> None:\n",
    "        self.public_data_url = public_data_url\n",
    "        self.fetch_json_path = fetch_json_path\n",
    "        # todo if folder not exist create folder structure\n",
    "        self.out_put_laz_path = \"./data/laz/temp.laz\"\n",
    "        self.out_put_tif_path = \"./data/tif/temp.tif\"\n",
    "\n",
    "    def __readFetchJson(self, path: str) -> dict:\n",
    "        try:\n",
    "            with open(path, 'r') as json_file:\n",
    "                dict_obj = json.load(json_file)\n",
    "            return dict_obj\n",
    "\n",
    "        except FileNotFoundError as e:\n",
    "            print(err_msgs['FETCH_JSON_FILE_NOT_FOUND'])\n",
    "\n",
    "    def getPipeline(self, region: str, bounds: Boundaries):\n",
    "        fetch_json = self.__readFetchJson(self.fetch_json_path)\n",
    "        BOUND = \"([-10425171.940, -10423171.940], [5164494.71, 5166494.71])\"\n",
    "\n",
    "\n",
    "#         boundaries = bounds.getBoundStr()\n",
    "\n",
    "        full_dataset_path = f\"{self.public_data_url}{region}/ept.json\"\n",
    "\n",
    "        fetch_json['pipeline'][0]['filename'] = full_dataset_path\n",
    "        fetch_json['pipeline'][0]['bounds'] = BOUND\n",
    "\n",
    "        fetch_json['pipeline'][3]['filename'] = self.out_put_laz_path\n",
    "        fetch_json['pipeline'][4]['filename'] = self.out_put_tif_path\n",
    "\n",
    "        pipeline = pdal.Pipeline(json.dumps(fetch_json))\n",
    "\n",
    "        return pipeline\n",
    "\n",
    "    def runPipeline(self, region: str, bounds: Boundaries):\n",
    "        pipeline = self.getPipeline(region, bounds)\n",
    "\n",
    "        try:\n",
    "            pipeline.execute()\n",
    "            metadata = pipeline.metadata\n",
    "            return pipeline.arrays\n",
    "        except RuntimeError as e:\n",
    "            print(e)\n",
    "\n",
    "    def __createDataFolderStruct(self):\n",
    "        # todo create folder structure for output folder\n",
    "        pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "a7eded13",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'Lidar_Data_Fetch2' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-17-bb7c14ed17fa>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     12\u001b[0m                   (MAXX, MAXY), (MAXX, MINY), (MINX, MINY)))\n\u001b[0;32m     13\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 14\u001b[1;33m \u001b[0mfetcher\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mLidar_Data_Fetch2\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mPUBLIC_DATA_URL\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     15\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     16\u001b[0m \u001b[1;31m# xmin, ymin = -10425171.940, -10423171.940\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'Lidar_Data_Fetch2' is not defined"
     ]
    }
   ],
   "source": [
    "from boundaries import Boundaries\n",
    "from shapely.geometry import Polygon\n",
    "\n",
    "\n",
    "REGION = \"IA_FullState\"\n",
    "PUBLIC_DATA_URL = \"https://s3-us-west-2.amazonaws.com/usgs-lidar-public/\"\n",
    "\n",
    "\n",
    "MINX, MINY, MAXX, MAXY = [-93.756155, 41.918015, -93.747334, 41.921429]\n",
    "\n",
    "polygon = Polygon(((MINX, MINY), (MINX, MAXY),\n",
    "                  (MAXX, MAXY), (MAXX, MINY), (MINX, MINY)))\n",
    "\n",
    "fetcher = Lidar_Data_Fetch2(PUBLIC_DATA_URL)\n",
    "\n",
    "# xmin, ymin = -10425171.940, -10423171.940\n",
    "# xmax, ymax = 5164494.710, 5166494.710\n",
    "# bounds = Boundaries(ymin, xmin, ymax, xmax)\n",
    "\n",
    "t = fetcher.runPipeline(REGION, polygon)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "ff4053f1",
   "metadata": {},
   "outputs": [],
   "source": [
    "MINX, MINY, MAXX, MAXY = [-93.756155, 41.918015, -93.747334, 41.921429]\n",
    "\n",
    "polygon = Polygon(((MINX, MINY), (MINX, MAXY),\n",
    "                  (MAXX, MAXY), (MAXX, MINY), (MINX, MINY)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "57830655",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "polygon_df = gpd.GeoDataFrame([polygon], columns=['geometry'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "82d7076c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>geometry</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>POLYGON ((-93.75616 41.91801, -93.75616 41.921...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                            geometry\n",
       "0  POLYGON ((-93.75616 41.91801, -93.75616 41.921..."
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "polygon_df.set_crs(epsg=3857, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "a2faef34",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0    POLYGON ((-0.00084 0.00038, -0.00084 0.00038, ...\n",
       "Name: geometry, dtype: geometry"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "polygon_df['geometry'].to_crs(epsg=4326)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "762f79aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_polygon_boundaries(polygon: Polygon):\n",
    "        polygon_df = gpd.GeoDataFrame([polygon], columns=['geometry'])\n",
    "\n",
    "        polygon_df.set_crs(epsg=4326, inplace=True)\n",
    "        polygon_df['geometry'] = polygon_df['geometry'].to_crs(\n",
    "            epsg=3857)\n",
    "        minx, miny, maxx, maxy = polygon_df['geometry'][0].bounds\n",
    "        # bounds: ([minx, maxx], [miny, maxy])\n",
    "        return f\"({[minx, maxx]},{[miny,maxy]})\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "ac7cdf00",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'([-10436887.43333523, -10435905.484106943],[5148706.389047224, 5149217.145836504])'"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "get_polygon_boundaries(polygon)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "66b4996e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_crop_polygon(polygon: Polygon):\n",
    "    polygon_cords = 'POLYGON(('\n",
    "    for i in list(polygon.exterior.coords):\n",
    "        polygon_cords += f'{i[0]} {i[1]},'\n",
    "\n",
    "    polygon_cords = polygon_cords[:-1] + '))'\n",
    "\n",
    "    return polygon_cords"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "aa6a4a59",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'temp' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-25-88edc2ec002c>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mget_crop_polygon\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpolygon\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m==\u001b[0m \u001b[0mtemp\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'temp' is not defined"
     ]
    }
   ],
   "source": [
    "get_crop_polygon(polygon) == temp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "a8239b9f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'POLYGON((-93.75615500000001 41.918015, -93.75615500000001 41.921429, -93.747334 41.921429, -93.747334 41.918015, -93.75615500000001 41.918015))'"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "''.join(str(polygon).split(\" \", 1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "d03ab264",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'(10, 11)' == str((10, 11))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "adc06ff9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"('a', 'b')\""
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "str(('a', 'b'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "da61664d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'((10, 11))'"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'((10, 11))'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "267018d6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'(10, 11)'"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "str((10, 11))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "fca92b19",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-33-e24737a900b0>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-33-e24737a900b0>\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    x = [list of x vals]\u001b[0m\n\u001b[1;37m              ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "x = [list of x vals]\n",
    "y = [list of y vals]\n",
    "\n",
    "some_poly = Polygon(x,y)\n",
    "\n",
    "# Extract the point values that define the perimeter of the polygon\n",
    "x, y = some_poly.exterior.coords.xy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "bb80474e",
   "metadata": {},
   "outputs": [],
   "source": [
    "temp = 'POLYGON(('\n",
    "xcord, ycord = polygon.exterior.coords.xy\n",
    "for x, y in zip(list(xcord), list(ycord)):\n",
    "    temp += f'{x} {y},'\n",
    "temp = temp[:-1]    \n",
    "temp += '))'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "6948bfa1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'POLYGON((-93.756155 41.918015,-93.756155 41.921429,-93.747334 41.921429,-93.747334 41.918015,-93.756155 41.918015))'"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "temp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f9a9c3b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
